### ISSUE TITLE
fails to build with ghc-9.6

### ISSUE THREAD

**Issue by juhp** [athanclark/fileneglect#1]
```
       Building library for follow-file-0.0.3..                                                                          [27/167012]       [2 of 2] Compiling System.File.Follow                                                                                        
                                                                  
       /var/stackage/work/unpack-dir/unpacked/follow-file-0.0.3-b22c2f8525f0bb26ca3286d6b34ff39056776896ce3be087a2817965fbe9172d/src
/System/File/Follow.hs:51:31: error: [GHC-83865]                                                                                    
           • Couldn't match expected type: unix-2.8.1.0:System.Posix.IO.Common.OpenFileFlags
                                           -> IO System.Posix.Types.Fd
                         with actual type: IO System.Posix.Types.Fd
           • The function ‘openFd’ is applied to four value arguments,
               but its type ‘RawFilePath
                             -> OpenMode                                                                                                                         -> unix-2.8.1.0:System.Posix.IO.Common.OpenFileFlags
                             -> IO System.Posix.Types.Fd’
               has only three                                     
             In the second argument of ‘($)’, namely                                                                                
               ‘openFd (BS8.fromString file') ReadOnly Nothing defaultFileFlags’
             In the first argument of ‘bracket’, namely                                                                             
               ‘(liftIO                                           
                   $ openFd (BS8.fromString file') ReadOnly Nothing defaultFileFlags)’
          |                                                                                                                         
       51 |   let go  = bracket (liftIO $ openFd (BS8.fromString file') ReadOnly Nothing defaultFileFlags)
          |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                                                                                                           /var/stackage/work/unpack-dir/unpacked/follow-file-0.0.3-b22c2f8525f0bb26ca3286d6b34ff39056776896ce3be087a2817965fbe9172d/src
/System/File/Follow.hs:51:70: error: [GHC-83865]
           • Couldn't match expected type ‘unix-2.8.1.0:System.Posix.IO.Common.OpenFileFlags’
                         with actual type ‘Maybe a0’
           • In the third argument of ‘openFd’, namely ‘Nothing’
             In the second argument of ‘($)’, namely
               ‘openFd (BS8.fromString file') ReadOnly Nothing defaultFileFlags’
             In the first argument of ‘bracket’, namely
               ‘(liftIO
                   $ openFd (BS8.fromString file') ReadOnly Nothing defaultFileFlags)’
          |
       51 |   let go  = bracket (liftIO $ openFd (BS8.fromString file') ReadOnly Nothing defaultFileFlags)
          |                                                                      ^^^^^^^
```
